/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as TripTypeRouteImport } from './routes/trip-type'
import { Route as TripDetailsRouteImport } from './routes/trip-details'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerSingleRouteImport } from './routes/planner-single'
import { Route as PlannerMultiRouteImport } from './routes/planner-multi'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollaborateRouteImport } from './routes/collaborate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTypeRoute = TripTypeRouteImport.update({
  id: '/trip-type',
  path: '/trip-type',
  getParentRoute: () => rootRouteImport,
} as any)
const TripDetailsRoute = TripDetailsRouteImport.update({
  id: '/trip-details',
  path: '/trip-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerSingleRoute = PlannerSingleRouteImport.update({
  id: '/planner-single',
  path: '/planner-single',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerMultiRoute = PlannerMultiRouteImport.update({
  id: '/planner-multi',
  path: '/planner-multi',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateRoute = CollaborateRouteImport.update({
  id: '/collaborate',
  path: '/collaborate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collaborate': typeof CollaborateRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/planner-multi': typeof PlannerMultiRoute
  '/planner-single': typeof PlannerSingleRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/trip-details': typeof TripDetailsRoute
  '/trip-type': typeof TripTypeRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collaborate': typeof CollaborateRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/planner-multi': typeof PlannerMultiRoute
  '/planner-single': typeof PlannerSingleRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/trip-details': typeof TripDetailsRoute
  '/trip-type': typeof TripTypeRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collaborate': typeof CollaborateRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/planner-multi': typeof PlannerMultiRoute
  '/planner-single': typeof PlannerSingleRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/trip-details': typeof TripDetailsRoute
  '/trip-type': typeof TripTypeRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/collaborate'
    | '/dashboard'
    | '/explore'
    | '/planner-multi'
    | '/planner-single'
    | '/profile'
    | '/results'
    | '/trip-details'
    | '/trip-type'
    | '/trips'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/collaborate'
    | '/dashboard'
    | '/explore'
    | '/planner-multi'
    | '/planner-single'
    | '/profile'
    | '/results'
    | '/trip-details'
    | '/trip-type'
    | '/trips'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/collaborate'
    | '/dashboard'
    | '/explore'
    | '/planner-multi'
    | '/planner-single'
    | '/profile'
    | '/results'
    | '/trip-details'
    | '/trip-type'
    | '/trips'
    | '/admin/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CollaborateRoute: typeof CollaborateRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  PlannerMultiRoute: typeof PlannerMultiRoute
  PlannerSingleRoute: typeof PlannerSingleRoute
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
  TripDetailsRoute: typeof TripDetailsRoute
  TripTypeRoute: typeof TripTypeRoute
  TripsRoute: typeof TripsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip-type': {
      id: '/trip-type'
      path: '/trip-type'
      fullPath: '/trip-type'
      preLoaderRoute: typeof TripTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip-details': {
      id: '/trip-details'
      path: '/trip-details'
      fullPath: '/trip-details'
      preLoaderRoute: typeof TripDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner-single': {
      id: '/planner-single'
      path: '/planner-single'
      fullPath: '/planner-single'
      preLoaderRoute: typeof PlannerSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner-multi': {
      id: '/planner-multi'
      path: '/planner-multi'
      fullPath: '/planner-multi'
      preLoaderRoute: typeof PlannerMultiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborate': {
      id: '/collaborate'
      path: '/collaborate'
      fullPath: '/collaborate'
      preLoaderRoute: typeof CollaborateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CollaborateRoute: CollaborateRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  PlannerMultiRoute: PlannerMultiRoute,
  PlannerSingleRoute: PlannerSingleRoute,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
  TripDetailsRoute: TripDetailsRoute,
  TripTypeRoute: TripTypeRoute,
  TripsRoute: TripsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
